### ISSUE TITLE
OG Pebble takes ~10secs to connect

### ISSUE THREAD

**Issue by dabanhfreak** [mattmattmatt/opus-pebble#39] opened 2016-06-16 16:16 UTC
I'm currently using Opus on the OG pebble, and opening the app I get a blank screen for about 5-10 seconds.  Sometimes I get the message "Can't connect, please open Pebble app on phone"

The Watch app eventually connects to Kodi, but the delay is quite an inconvenience.

**Comment by mattmattmatt** [comment] 2016-06-16 16:30
I'm sorry to hear that.

When the app opens, Opus tries to immediately connect to Kodi, which requires the Bluetooth connection to your phone to be active. If your phone is far away from your watch or experiencing signal shielding from e.g. your body, that could be a reason for the slow connection time. 

What happens if you load Opus (successfully), exit out of the app and load it up immediately again? Is the loading time shorter/instant?

Unfortunately, I don't have an OG pebble so can't reproduce.

**Comment by dabanhfreak** [comment] 2016-06-16 16:44
Thanks for the quick reply.  Yeah I just tried it now and it loaded within 1-2 seconds.
I believe it's mainly when I open the app after a few hours.

Do you have any plans to develop this app further?  I'm thinking if you have Opus check for Android notifications it can work with Yatse, kinda what the stock music app does with Google Play Music.

**Comment by mattmattmatt** [comment] 2016-06-16 17:09
That points at either your watch not being connected immediately when you try to open the app or the OG pebble just being slow at loading the full app into memory (which could be the case as the hardware is much more limited than e.g. the Pebble Time).
I'm afraid there is nothing I can do about this in the short term.

In the bigger picture, however, I am currently looking into extending Opus with more features and rewriting it in C. I assume this would speed up the loading process notably, as there is no phone connection needed for the initial loading of the app. For the actual connection to Kodi, however, the phone is necessary.

Can I ask what you mean with "check for Android notifications with Yatse"? I use Yatse myself but wanted to keep this watchapp independent of 3rd party apps (also to make it more useful iPhone users).

**Comment by dabanhfreak** [comment] 2016-06-16 17:33
Looking forward to your update, I'm backing the new Pebble on Kickstarter so hopefully the limitations will be less apparent.

By notification check, I believe Music Boss works by noticing when Google Play music starts, and also when the Android is connected to Chromecast (it controls it this way).  I believe the quick controls in the notifications allows it to do this.

Yatse has a notification when media is playing; perhaps Opus can automatically fire up when media starts using this as a trigger.

**Comment by mattmattmatt** [comment] 2016-06-16 23:26
I'm sure the new Pebble 2 and Time 2 will have much faster and seamless experiences for you. I saw the Pebble 2 in SF yesterday and it looks great (for a b/w watch).

Regarding auto-open based on phone notification activity, Music Boss can offer that because there is a corresponding Android app installed on the phone. Without an app, this functionality is not possible.
I think it's a great feature that I would also like to have but at this point I'm not looking into creating a companion app. I will be looking into other ways to make this possible, though.

If you don't mind I will close this issue for now as there is not much I can do about your original problem.

**Closed as completed by mattmattmatt** 2016-06-16 23:26 UTC

**Comment by dabanhfreak** [comment] 2016-06-17 01:29
Thanks for your feedback, looking forward to your work!
