### ISSUE TITLE
Config won't save host settings

### ISSUE THREAD

**Issue by 8a5** [mattmattmatt/opus-pebble#36] opened 2016-03-12 17:06 UTC
I try to add a host but it won't get saved.

**Comment by mattmattmatt** [comment] 2016-05-17 07:19
If this problem was caused by #37, please give it another try.

Otherwise I would be curious to hear what kind of values you are inputting that lead to your bug.

I will close this issue until then, feel free to keep commenting.

**Closed as completed by mattmattmatt** 2016-05-17 07:19 UTC
